### ISSUE TITLE
Loops do not work loops are skipped

### ISSUE THREAD

**Issue by rdebath** [nicolas93/brainfuck#6]
Similar to #1, this program should print "Hello World!"
``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by nicolas93** [comment]
The bug was, that the loops were implemented as `do{}while()` instead of `while(){}`.
The given example now outputs "Hello World!" as it is supposed to.
